controllers/DashboardController.php
<?php

namespace app\controllers;

use yii;
use yii\web\User;
use app\models\Campaign;
use app\models\search\FundCampaignSearch;
use app\models\search\CampaignSearch;
use app\models\FundCampaign;
use yii\data\Pagination;
use yii\data\ActiveDataProvider;

class DashboardController extends \yii\web\Controller
{

    public function behaviors()
{
    return [
        'access' => [
            'class' => AccessControl::className(),
            'rules' => [
                [
                    'actions' => ['list'],
                    'allow' => true,
                    'roles' => ['@'],
                ],
            ], // rules
        ], // access
    ];
}
    public function actionIndex()
    {

        $connection = Yii::$app->getDb();
        $userId = Yii::$app->user->identity->id;
         echo '<pre>'; var_dump($userId); echo '</pre>'; exit;
        $campaigns    = new Campaign();
        $fundCampaign = new FundCampaign();

        $my_activecampaignCount = $campaigns::find()->where(['is_active'=> 1, 'created_by'=> $userId])->count();

        $myactivecampaigns = $connection->createCommand( " select c.title,c.id,c.token,c.is_active,c.description,l.name state_name,c.created_time, (select sum(fc.foodstamp_volume) from fund_campaign fc where fc.campaign_id=c.id) volume, (select count(*) from voucher_batch_pins v where v.is_used=1 and v.campaign_id=c.id) used from campaign c,lga l where c.is_active=1 and l.id=c.location and c.created_by= $userId order by c.id desc")->queryAll(); 

        $mydonations  = $connection->createCommand("select ifnull(sum(t.volume),0) from transaction t where t.donor_id= $userId and !isnull(t.complete_time) and description='TOPUP'")->queryScalar();

        $mybalance    = $connection->createCommand("select sum( IF(description='TOPUP',t.volume,0) )+ sum( IF(description='DEBIT',t.volume,0) ) from transaction t where t.donor_id= $userId and !isnull(t.complete_time)")->queryScalar();

        $mealserved   = $connection->createCommand("select count(*) from campaign c, voucher_batch_pins v where v.campaign_id=c.id and c.created_by= $userId and v.is_activated=1 and v.is_used=1 and (select count(*) from fund_campaign fc where fc.batch_token=v.batch_id limit 1)=1 and (select count(*) from fund_campaign fc where fc.batch_token=v.batch_id limit 1)=1")->queryScalar();
       
        $mealunserved = $connection->createCommand("select count(*) from campaign c, voucher_batch_pins v where v.campaign_id=c.id and c.created_by= $userId and v.is_activated=1 and isnull(v.is_used) and (select count(*) from fund_campaign fc where fc.batch_token=v.batch_id limit 1) = 1 ")->queryScalar();

        $myCampaign2   = $campaigns::find()->where(['created_by'=> $userId ]);

        $myCampaignCount   = $myCampaign2->count();
        
        $model = new CampaignSearch();
        $data = $model->search(Yii::$app->request->queryParams);
        

        $this->layout = "main";
        

         return $this->render('index', [
            'mealunserved' => $mealunserved,
            'my_activecampaignCount' => $my_activecampaignCount,
            'myactivecampaigns' => $myactivecampaigns,
            'mydonations' => $mydonations,
            'mybalance' => $mybalance,
            'mealserved' => $mealserved,
            'user' => $userId,
            'data' => $data,
            'pagination' => $data->pagination
        ]);
    }
    
    public function actionMyFundedCampaigns(){
        $connection = Yii::$app->getDb();
        $fundCampaignSearch = new FundCampaignSearch();
        
        $model = $fundCampaignSearch->search(Yii::$app->request->queryParams);
        $user = Yii::$pp->user->identity->id;
        $my_activecampaignCount = $campaigns::find()->where(['is_active'=> 1, 'created_by'=> $userId])->count();

      
        $myFundedCampaigns = $connection->createCommand("select c.title,c.id,c.token,c.is_active,c.description,s.name state_name,c.created_time,
                sum(fc.foodstamp_volume) volume,fc.batch_token,
                (select count(*) from voucher_batch_pins v where v.is_used = 1 and v.campaign_id = c.id and v.donor_id = $user) used from campaign c, lga s, fund_campaign fc, users u
                where c.is_active = 1 and fc.campaign_id = c.id and !ISNULL(fc.batch_token) 
                and fc.created_by =  $user and s.id = c.location and u.id = c.channel_partner_id group by c.id order by fc.id desc")->queryAll();

        $mydonations = $connection->createCommand("select ifnull(sum(t.volume),0) from transaction t where t.donor_id=  $users and !isnull(t.complete_time) and description='TOPUP'")->queryScalar();
        $mealserved   = $connection->createCommand("select count(*) from campaign c, voucher_batch_pins v where v.campaign_id=c.id and c.created_by= $userId and v.is_activated=1 and v.is_used=1 and (select count(*) from fund_campaign fc where fc.batch_token=v.batch_id limit 1)=1 and (select count(*) from fund_campaign fc where fc.batch_token=v.batch_id limit 1)=1")->queryScalar();
        $mealunserved = $connection->createCommand("select count(*) from campaign c, voucher_batch_pins v where v.campaign_id=c.id and c.created_by= $userId and v.is_activated=1 and isnull(v.is_used) and (select count(*) from fund_campaign fc where fc.batch_token=v.batch_id limit 1) = 1 ")->queryScalar();


        $fcm = new FundCampaign('search');
        //$model->unsetAttributes();  // clear any default values
        

      

      return $this->render('my-funded-campaigns', array( 
          'myFundedCampaigns'=>$myFundedCampaigns, 
          'myFundedCampaignsCount'=>$myFundedCampaignsCount, 
          'mydonations'=>$mydonations,
           'mealserved'=>$mealserved, 
           'mealunserved'=>$mealunserved,
           
        ));
    }


}

views/dashboard/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;

?>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="pagetitle ">
                <span class="pagetitle__title">Dashboard</span>
                <div class="btn1">
                    <a href="<?php echo Yii::$app->urlManager->createUrl('') ?>" class="pagetitle__button">Fund Campaign</a>
                </div>
                <div class="btn2">
                    <a href="<?php echo Yii::$app->urlManager->createUrl('') ?>" class="pagetitle__button">Create A Campaign</a>
                </div>
                <div class="btn2">
                    <a href="<?php echo Yii::$app->urlManager->createUrl('') ?>" class="pagetitle__button">Top Up Account</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container data-card-list">
    <?php if (isset($this->msg)) { ?>
        <div class="alert alert-success">
            <?php echo $this->msg ?>
        </div>
    <?php } ?>
    <?php if (isset($this->err)) { ?>
        <div class="alert alert-warning">
            <?php echo $this->err ?>
        </div>
    <?php } ?>

 

    <div class="row">
        <div class="col-sm-3 col-xs-12">
            <div class="data-card-list__list" style="border-radius: 15px;">
                <img style="" src="<?php echo Yii::$app->request->baseUrl; ?>/assets/image/gfs-icons-campaign.png">
                <span class="data-card-list__title"><?php echo $my_activecampaignCount?></span>
                <span class="data-card-list__info">My campaign</span>
            </div>
        </div>
        <div class="col-sm-3 col-xs-12">
            <div class="data-card-list__list" style="border-radius: 15px;">
                <img style="" src="<?php echo Yii::$app->request->baseUrl; ?>/assets/image/gfs-icons-meal.png">
                <span class="data-card-list__title"><?php echo $mealserved ?></span>
                <span class="data-card-list__info">Meal served</span>
            </div>
        </div>
        <div class="col-sm-3 col-xs-12">
            <div class="data-card-list__list" style="border-radius: 15px;">
                <img style="" src="<?php echo Yii::$app->request->baseUrl; ?>/assets/image/gfs-icons-meal.png">
                <span class="data-card-list__title"><?php echo  $mealunserved ?></span>
                <span class="data-card-list__info">Meals unserved</span>
            </div>
        </div>
        <div class="col-sm-3 col-xs-12">
            <div class="data-card-list__list" style="border-radius: 15px;">
                <img style="" src="<?php echo Yii::$app->request->baseUrl; ?>/assets/image/gfs-icons-stamp.png">
                <span class="data-card-list__title"><?php echo $mybalance ?></span>
                <span class="data-card-list__info">Available stamps</span>
            </div>
        </div>
        <div class="col-sm-2 col-xs-12">
       <!--     <div class="data-card-list__list">
                <img style="" src="<?php echo Yii::$app->request->baseUrl; ?>/assets/image/gfs-icons-campaign.png">
                <span class="data-card-list__title"><?php echo (isset($mydonations) && isset($mydonations->object)) ? number_format($mydonations->object) : '0' ?></span>
                <span class="data-card-list__info">Total donation</span>
            </div>
        </div>-->
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="tab-menu">
                <span class="tab-menu__item">
                    <a href="#" class="active">My Campaigns</a>
                </span>
                <span class="tab-menu__item">
                    <a href="<?php echo Yii::$app->urlManager->createUrl('dashboard/my-funded-campaigns') ?>">Funded Campaigns</a>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="container block-list">
    <div class="row">
        <div class="col-xs-12">
                <?php
                foreach ($data->getModels() as $cd) { ?>
                    <a href="<?php echo Yii::$app->urlManager->createUrl('donor/viewCampaign', array('token' => $cd->token) ) ?>" class="block-list__list">
                        <?php if ($cd->is_active == 1) { ?>
                            <div class="block-list__left-holder">
                                <i class="fa fa-play"></i>
                            </div>
                        <?php } else { ?>
                            <div class="block-list__left-holder">
                                <i class="fa fa-stop"></i>
                            </div>   
                        <?php } ?>
                        <div class="block-list__right-holder">
                            <span class="main">Donation: <?php echo $cd->volume ?>, Used: Used Food Stamps</span>
                            <div class="progress-bar-green">
                                <span class="progress-bar-filler" style="width: <?php echo ($cd['volume'] == 0 ? 0 : ((($cd['used'] * 100) / $cd['volume']) )) ?>%;"></span>
                            </div>
                        </div> 
                        <div class="block-list__main-holder">
                            <div class="block-list__title"><?php echo $cd->title ?></div>
                            <div class="block-list__info">Created: <?php echo $cd->created_time ?> | Location: <?php //echo $cd->state_name ?></div>
                        </div>
                    </a>
                <?php } ?>
                   <?= LinkPager::widget(['pagination' => $pagination,]); ?>
        </div>
    </div>
</div>

views/dashboard/my-funded-campaigns.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;

?>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="pagetitle">
                <span class="pagetitle__title">Funded Campaigns</span>
                <a href="<?php echo Yii::app()->createUrl('donor/createCampaign') ?>" class="pagetitle__button btn btn-info">Create A Campaign</a>
            </div>
        </div>
    </div>
</div>

<div class="container data-card-list">
    <?php if (isset($this->msg)) { ?>
        <div class="alert alert-success">
            <?php echo $this->msg ?>
        </div>
    <?php } ?>
    <?php if (isset($this->err)) { ?>
        <div class="alert alert-warning">
            <?php echo $this->err ?>
        </div>
    <?php } ?>
    


    <div class="row">
        <div class="col-sm-3 col-xs-12">
            <div class="data-card-list__list">
                <span class="data-card-list__title"><?php echo $myFundedCampaignsCount ?></span>
                <span class="data-card-list__info">My Funded Campaign</span>
            </div>
        </div>
        <div class="col-sm-3 col-xs-12">
            <div class="data-card-list__list">
                <span class="data-card-list__title"><?php echo $mealserved ?></span>
                <span class="data-card-list__info">Meal Served</span>
            </div>
        </div>
        <div class="col-sm-3 col-xs-12">
            <div class="data-card-list__list">
                <span class="data-card-list__title"><?php echo $mealunserved ?></span>
                <span class="data-card-list__info">Meal Unserved</span>
            </div>
        </div>
        <div class="col-sm-3 col-xs-12">
            <div class="data-card-list__list">
                <span class="data-card-list__title"><?php echo $mydonations ?></span>
                <span class="data-card-list__info">Stamps Donated</span>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="tab-menu">
                <span class="tab-menu__item">
                    <a href="<?php echo $this->createUrl('donor/dashboard') ?>">My Campaigns</a>
                </span>
                <span class="tab-menu__item">
                    <a  class="active" href="<?php echo $this->createUrl('donor/myFundedCampaigns') ?>">Funded Campaigns</a>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="container block-list">

    <div class="row">
        <div class="col-xs-12">
            
                <?php
                foreach ( $myFundedCampaigns as $myactivecampaign) { ?>
                    <a href="<?php echo $this->createUrl('donor/viewOtherCampaign', array('token' => $myactivecampaign['token'])) ?>" class="block-list__list">
                        <?php if ($myactivecampaign['is_active'] == 1) { ?>
                            <div class="block-list__left-holder">
                                <i class="fa fa-play"></i>
                            </div>
                        <?php } else { ?>
                            <div class="block-list__left-holder">
                                <i class="fa fa-stop"></i>
                            </div>   
                        <?php } ?>
                        <div class="block-list__right-holder">
                            <span class="main">Donation: <?php echo $myactivecampaign['volume'] ?>, Used: <?php echo $myactivecampaign['used']?> Food Stamps</span>
                            <div class="progress-bar-green">
                                <span class="progress-bar-filler" style="width: <?php echo ($myactivecampaign['volume'] == 0 ? 0 : ((($myactivecampaign['used'] * 100) / $myactivecampaign['volume']) )) ?>%;"></span>
                            </div>
                        </div>
                        <div class="block-list__main-holder">
                            <div class="block-list__title"><?php echo $myactivecampaign['title'] ?></div>
                            <div class="block-list__info">Created: <?php echo $myactivecampaign['created_time'] ?> 
                                | Location: <?php echo $myactivecampaign['state_name'] ?></div>
                        </div>
                    </a>

                <?php } ?>

              

        </div>
    </div>
</div>