controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Users;
use app\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\ActiveQuery;
use app\models\Campaign;
use app\models\Country;
use app\models\Contact;
use app\models\State;
use app\models\LoginForm;
use app\models\Lga;
use app\models\User;
use app\models\CampaignGallery;
use app\models\search\CampaignGallerySearch;
use app\models\search\VideoSearch;
use app\models\FundCampaign;
use app\models\Video;
use yii\data\ActiveDataProvider;
use app\controllers\CHttpException;
use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;
use yii\base\ErrorException;


/**
 * SiteController implements the CRUD actions for Users model.
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = "main";
        return $this->render('home');
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    
    public function actionContact() {
        $contact = new Contact();
        $session = Yii::$app->session;
        
        if($contact->load(Yii::$app->request->post())){
          
          if($contact->save(false)){
             $session->setFlash('success', 'Thank You For Contacting Us. Your Message has been received');
          }else{
            $session->setFlash('error','We\'re sorry, something went wrong');
          }
          
          return $this->redirect('contact');
        }
        
        return $this->render('contact', [
            'contact' => $contact
        ]);
    }
    
    public function actionCampaigns()
    {

        $CampaingSearchModel = new \app\models\search\CampaignSearch();

        $dataProvider =  $CampaingSearchModel->search(Yii::$app->request->queryParams);

        return $this->render('campaigns', [
            'searchModel' =>  $CampaingSearchModel,
            'dataProvider' => $dataProvider,
            'pagination' => $dataProvider->getPagination(),
            'models' => $dataProvider->getModels()
        ]);
    }
    public function actionViewCampaign()
    {
        $token = Yii::$app->request->get('token');
        $campaign = Campaign::findOne(['token' => $token]);
        $totalDonations = FundCampaign::find()->totalCampaignDonation($campaign->id);
        $served = FundCampaign::find()->totalServedDonation($campaign->id);
        $donors = FundCampaign::find()->totalDonor($campaign->id);
        $images = CampaignGallery::findBySql('select * from campaign_gallery order by id desc limit 4')->all();
        $videos = Video::findBySql('select * from video order by id desc limit 4')->all();


        $provider = new ActiveDataProvider(['query' =>  FundCampaign::find()
                ->where(['campaign_id' => $campaign->id]), 'pagination' => ['pageSize' => 3], 'sort' => ['defaultOrder' => ['create_time' => SORT_DESC]]]);
        $recentDonations = $provider->getModels();

        return $this->render(
            'viewcampaign',
            [
                'campaign' => $campaign,
                'totalDonations' => $totalDonations,
                'donors' => $donors,
                'served' => $served,
                'images' => $images,
                'videos' => $videos,
                'recentDonations' => $recentDonations,
                'provider' => $provider,
            ]
        );
    }

     public function actionViewCampaignImage($token)
    {
        $campaign = Campaign::findOne(['token' => $token]);
        
        $model = new CampaignGallerySearch();
        $imageGallery = $model->search(Yii::$app->request->queryParams);

        return $this->render('viewCampaignImage', [
            'campaign' => $campaign,
            'model' => $model,
            'imageGallery' => $imageGallery,
            'pagination' => $imageGallery->pagination
        ]);
    }
    
    public function actionViewCampaignVideo($token){
      
        $campaign = Campaign::findOne(['token' => $token]);
        
        $model = new VideoSearch();
        $videoGallery = $model->search(Yii::$app->request->queryParams);
        
          return $this->render('viewCampaignVideo', [
            'campaign' => $campaign,
            'model' => $model,
            'videoGallery' => $videoGallery,
            'pagination' => $videoGallery->pagination
        ]);
    }

    /* Methods for links on the NavBar from how-it-works*/
    public function actionHowItWorks(){
        return $this->render('HowItWorks');
    }
            public function actionAbout()
            {
                return $this->render('about');
            }

            public function actionStakeholders(){
                return $this->render('stakeholders');
            }

            public function actionBoard(){
                return $this->render('board');
            }
    /* End of methods for links */


    public function actionFoodVendorMap()
    {

        $connection = Yii::$app->getDb();

        $countryLists = Country::findBySql("select c.*,(select count(*) from food_vendors fv where fv.country = c.name) cnt from country c where c.is_active = 1")->all();


        $stateLists = $connection->createCommand('select *,(select count(*) from food_vendors fv where fv.city_id = s.id) cnt from state s where s.country_id = :country')
            ->bindValue('country', Yii::$app->request->get('country'))->queryAll();


        $lgaLists = $connection->createCommand('select *, (select count(*) from food_vendors fv where fv.lga = lg.name) cnt from lga lg where lg.state_id =:state')
            ->bindValue('state', Yii::$app->request->get('state'))->queryAll();


        return $this->render('FoodVendorMap', array(
            'countryLists' => $countryLists,
            'stateLists' => $stateLists,
            'lga' => $lgaLists
        ));
    }

    public function actionFoodvendorjson()
    {
        $connection = Yii::$app->getDb();
        $country = Yii::$app->request->get('country');
        $state = Yii::$app->request->get('state');
        $lga = Yii::$app->request->get('lga');

        $c = Country::findByAttributes(['id' => $country]);

        $l = Lga::model()->findByAttributes(['id' => $lga]);

        $ar = $connection->createCommand('select fv.first_name,fv.sur_name,fv.business_name,fv.addr_line_i,fv.addr_line_ii,fv.landmark,fv.lga,fv.country,fv.x_coordinate,fv.y_coordinate from food_vendors fv where fv.city_id = :state and fv.lga = :lga and fv.country = :country')
            ->bindValue('country', $c->name)
            ->bindValue('state', $state)
            ->bindValue('lga', $l->name)
            ->queryAll();

        header('Content-type: application/json');
        echo CJavaScript::jsonEncode($ar);
    }



     /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionRegister()
    {
        $model = new Users();
        $session = Yii::$app->session;

        if ($model->load(Yii::$app->request->post())) {

            if($model->password != filter_input(INPUT_POST, 'confirmPassword')){

                $session->set('pwdError', 'Confirm password differs from password');
                $pwdError = $session;
                $this->redirect('register');
            }

            $model->token = uniqid();
            $model->password = md5($model->password);
            $model->save(false);
            $this->redirect(Yii::$app->urlManager->createUrl('dashboard'));
        }
        return $this->render('register', ['model'   => $model, /*'pwdError' => $pwdError*/ ]);
    }

    public function actionLogin()
    {
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post())){
            if($model->login()) {
                return $this->goBack();
            }
        }
        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

/* ------------------------------------------------------------------------------------- */    
    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionStateList($id){
        
        $countOfStates =  State::find()->where(['id' => $id])->count();
        $states =  State::find()->where(['id'=> $id])->all();
        
        if($countOfStates > 0){
            foreach($states  as $state ){

views/site/FoodVendorMap.php
<?php
/*
 * 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/* @var $this SiteController */
?>
<style>
    #map {
        width: 100%;
        height: 400px;
        background-color: grey;
    }
    .containerM{
        width: 54%;
        float: left;
        padding: 1px 1px 1px 100px;
        left: 75px;
        /* background-color: #eee; */
        top: 65%;

    }


    .Mapview{
        height: 400px;
        padding: 0 0 0 750px;
    }
    .boxed {
        border: 1px solid green ;
        width: 71%
    }


    #containerA {
        margin: 0 auto;
        width: 35%;
    }
    #accordion input {
        display: none;
    }
    #accordion label {
        background: #CFC;
        border-radius: .25em;
        cursor: pointer;
        display: block;
        margin-bottom: .125em;
        padding: 2.25em 1em;
        z-index: 20;
    }
    #accordion label:hover {
        background: #ccc;
    }

    #accordion input:checked + label {
        background: #ccc;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
        color: white;
        margin-bottom: 0;
    }
    #accordion article {
        background: #f7f7f7;
        height:0px;
        overflow:hidden;
        z-index:10;
    }
    #accordion article p {
        padding: 1em;
    }
    #accordion input:checked article {
    }
    #accordion input:checked ~ article {
        border-bottom-left-radius: .25em;
        border-bottom-right-radius: .25em;
        height: auto;
        margin-bottom: .125em;
    }



</style>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="pagetitle">
                <span class="pagetitle__title">Food Vendors Network</span>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-4"  style="margin-bottom: 10px;">
                <select id="country" class="form-control btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <option value="">--Select Country--</option>
                    <?php foreach ($countryLists as $countryList) { ?>
                          <option value="<?= $countryList->id ?>">
                          <?php echo $countryList->name . ' - vendors: '. $countryList->cnt ?>
                        </option>        
                    <?php } ?>
                </select>
            </div>
            <div class="col-md-4" style="margin-bottom: 10px;">
                <select id="state"class="form-control  btn btn-secondary dropdown-toggle col-md-12"   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <option value="">--Select State--</option>               
                    <?php foreach ($stateLists as $s) { ?>
                        <option <?php echo Yii::$app->request->get("state") == $s['id'] ? "selected" : "" ?> value="<?php echo $s['id']; ?>">
                            <?php echo $s['name'] . ' - vendors: ' . $s['cnt']; ?>
                        </option>
                    <?php } ?>
                </select>
            </div>
            <div class="col-md-4" style="margin-bottom: 10px;">
                <select id="lga" class="form-control  btn btn-secondary dropdown-toggle col-md-12"   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <option value="">--Select LGA--</option>
                    <?php foreach ($lga as $lg) { ?>
                        <option <?= Yii::$app->request->get("lga") == $lg['id'] ? "selected" : "" ?> value="<?= $lg['id']; ?>">
                            <?php echo $lg['name'] . ' - vendors: ' . $lg['cnt']; ?>
                        </option>
                    <?php } ?>
                </select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div id="demo" class="collapse">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12" style="vertical-align:top;text-align:right;">
            <div id="map"></div>
        </div>
    </div>
</div>

<script>
    function initMap() {
        var locations = [];


        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: new google.maps.LatLng(6.5244, 3.3792),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });

        google.maps.event.addListener(map, 'dragend', function () {
            window.console.log("Map clicked");
        });



        var infowindow = new google.maps.InfoWindow();

        var markers, i;

        var image = {
            url: 'http://www.tow411.net/images/dotred.gif',
            size: new google.maps.Size(12, 12),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(0, 32)
        };

        var shape = {
            coords: [1, 1, 1, 20, 18, 20, 18, 1],
            type: 'poly'
        };


        var myUrl = $(location).attr('href');
        var vendorList = myUrl;
        vendorList = vendorList.replace("Map", "json")
        $.getJSON(vendorList, function (data) {
            var items = [];
            console.log(data);

            var i = 0;
            $.each(data, function (key, val) {
                if (i == 0) {
                    var center = new google.maps.LatLng(val.x_coordinate, val.y_coordinate)
                    map.panTo(center);
                }
                markers = new google.maps.Marker({
                    position: new google.maps.LatLng(val.x_coordinate, val.y_coordinate),
                    map: map,
                    icon: image,
                    // title: locations[i][0],
                    shape: shape
                });

                google.maps.event.addListener(markers, 'mouseover', (function (markers, i) {
                    return function () {
                        infowindow.setContent(val.first_name + " " + val.sur_name
                                + "<br>" + val.business_name
                                + "<br>" + val.addr_line_i + ", " + " " + val.landmark);
                        infowindow.open(map, markers);
                    }
                })(markers, i));
                i++
            });

        });

    }

    /* When the user clicks on the button, 
     toggle between hiding and showing the dropdown content */
    function myFunction() {
        document.getElementById("CountDrop").classList.toggle("show");
    }

    // Close the dropdown if the user clicks outside of it
    window.onclick = function (event) {
        if (!event.target.matches('.dropbtn')) {

            var dropdowns = document.getElementsByClassName("Count-drop");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }




    const currentURL = document.URL;

    var myUrl = $(location).attr('href');

    function addQSParm(name, value) {
        var re = new RegExp("([?&]" + name + "=)[^&]+", "");
        function add(sep) {
            myUrl += sep + name + "=" + encodeURIComponent(value);
        }

        function change() {
            myUrl = myUrl.replace(re, "$1" + encodeURIComponent(value));
        }
        if (myUrl.indexOf("?") === -1) {
            add("?");
        } else {
            if (re.test(myUrl)) {
                change();
            } else {
                add("&");
            }
        }
    }

    function removeQSParm(name) {
        var re = new RegExp("([?&]" + name + "=)[^&]+", "");
        myUrl = myUrl.replace(re, "");
    }

    viewTab = function (j, val) {

        switch (j) {
            case "country":
                console.log("country");
                addQSParm("country", val);
                break;
            case "state":
                addQSParm("state", val);
                console.log("state");
                break;
            case "lga":
                addQSParm("lga", val);
                console.log("lga");
                break;
        }
        location.href = myUrl;
        console.log(myUrl);
    };



    $(document).ready(function () {

        $('#country').change(function () {
            console.log($(this).val())
            viewTab("country", $(this).val())
        });

        $('#state').change(function () {
            viewTab("state", $(this).val())
        });

        $('#lga').change(function () {
            viewTab("lga", $(this).val())
        });
    });

</script>




<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCb9JS0wCQvknCAgr0EaB-KZZhe-a27sOA&callback=initMap">
</script>

views/site/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UsersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'firstname') ?>

    <?= $form->field($model, 'lastname') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'password') ?>

    <?php // echo $form->field($model, 'account_type') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'state') ?>

    <?php // echo $form->field($model, 'lga') ?>

    <?php // echo $form->field($model, 'token') ?>

    <?php // echo $form->field($model, 'last_login') ?>

    <?php // echo $form->field($model, 'user_type') ?>

    <?php // echo $form->field($model, 'organisation_name') ?>

    <?php // echo $form->field($model, 'organisation_category_id') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'operating_state') ?>

    <?php // echo $form->field($model, 'contact_number') ?>

    <?php // echo $form->field($model, 'parent_id') ?>

    <?php // echo $form->field($model, 'country_id') ?>

    <?php // echo $form->field($model, 'confirm_time') ?>

    <?php // echo $form->field($model, 'created_time') ?>

    <?php // echo $form->field($model, 'updated_time') ?>

    <?php // echo $form->field($model, 'is_active') ?>

    <?php // echo $form->field($model, 'is_approve') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/board.php
            <div class="container">
                <div class="wrapper">
                    <div class="row row-offcanvas row-offcanvas-left gfs-inner">
                        <!-- sidebar -->
                        <div class="column col-sm-3 col-xs-1 sidebar-offcanvas" id="sidebar">
                            <ul class="nav" id="menu">
                                <li><a href="<?= Yii::$app->urlManager->createAbsoluteUrl('site/about') ?>" ><span class="collapse in hidden-xs">About</span></a></li>
                                <li><a href="<?= Yii::$app->urlManager->createAbsoluteUrl('site/how-it-works') ?>" > <span class="collapse in hidden-xs">How it Works</span></a></li>
                                <li><a href="<?= Yii::$app->urlManager->createAbsoluteUrl('site/stakeholders') ?>"> <span class="collapse in hidden-xs">Stakeholders</span></a></li>
                                <li><a href="<?= Yii::$app->urlManager->createAbsoluteUrl('site/board') ?>" class="active"><span class="collapse in hidden-xs">Board</span></a></li>

                            </ul>
                        </div>
                        <!-- /sidebar -->

                        <!-- main right col -->
                        <div class="column col-sm-9 col-xs-12" id="main">
                            <a href="#" data-toggle="offcanvas"><i class="fa fa-navicon fa-2x"></i></a>
                            <h1 class="big-title" id="about" >Board</h1>
                            <hr/>

                            <article class="regular-text-left">

                               <!-- <img style="" src="<?php echo Yii::$app->request->baseUrl; ?>/assets/image/wumi.jpg"> -->
                                
                                
                                <h4 class="regular-text-left"><b>Wumi Oghoetuoma (Founder/Chairman)</b></h4>
                                <p class="regular-text-left">A graduate of Computer Science from Kingston University in the UK in 2001
                                    He built his career as a Business Analyst and has been a Technology Solutions Designer across Europe, Australia & Africa for top companies such as AOL, Virgin Media, Tele2, Thomson Reuters & Altech Multimedia and more
                                    He founded Crown Interactive where he still serves as Director and raised equity investment as a technology entrepreneur and moved to Nigeria to design and implement proudly Nigerian Solutions for Developing Country Issues in the public and private sector. Wumi leads the design of solutions in the telecoms and power sector and now for citizens’ welfare</p>

                                 <!--<img style=""float: left;" src="<?= Yii::$app->request->baseUrl; ?>/assets/image/w"> -->  
                                <h4 class="regular-text-left"><b>Toyin Oghoetuoma (Co-Founder)</b></h4>
                                <p class="regular-text-left">A graduate of Business Information Technology at London Metropolitan University in the UK in 2002
                                    Her first job as a graduate was in one of the top banks in United Kingdom in Business Operations. She worked there for some years until she ventured into entrepreneurship and relocated to Nigeria in 2012
                                    A passionate media enthusiast spearheading online media interactivity for major global clients. She is the CEO of Tozaza Media Ltd, a media company in Lagos Nigeria that provides online multimedia and streaming solutions to corporate companies
                                    She is passionate about children’s lifestyle in education and has therefore participated at executive levels in Parents Advisory Committees for schools. Toyin has a passion for social enterprise with a focus on innovative food distribution for poverty alleviation</p>

                                <h4 class="regular-text-left"><b>Chinwe Onubogu LLM, ACIS (Co-Founder)</b></h4>
                                <p class="regular-text-left">A practicing Solicitor and Chartered Secretary based in Lagos, Nigeria. She obtained a degree in Law (LLB) from Enugu State University of Science and Technology in 2002. She was admitted to practice as a Barrister and Solicitor of the Supreme Court of Nigeria in 2005
                                    She holds a Master’s Degree (LLM) in Commercial law from University of Witwatersrand, Johannesburg SA
                                    She is the Founder and Managing Director of Zuriel Consulting Limited and Managing Partner of ZCL Solicitors a legal consulting and professional services firm with a focus on SMEs.  She has a passion for social enterprise and high impact investments</p>
                            </article>
                        </div>
                        <!-- /main -->
                    </div>
                </div>
            </div>

views/site/coming_soon.php
<html>
    <title>Coming Soon</title>
    <body style="text-align: center"><img src="assets/image/comingsoon.png" ></body>

</html>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */



use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">
    <div class="container">
        <h1><?= Html::encode($this->title) ?></h1>

        <div class="alert alert-danger">
            <?= nl2br(Html::encode($message)) ?>
        </div>

        <p>
            The above error occurred while the Web server was processing your request.
        </p>
        <p>
            Please contact us if you think this is a server error. Thank you.
        </p>
    </div>
</div>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Users', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'firstname',
            'lastname',
            'email:email',
            'password',
            //'account_type',
            //'address',
            //'state',
            //'lga',
            //'token',
            //'last_login',
            //'user_type',
            //'organisation_name',
            //'organisation_category_id',
            //'description:ntext',
            //'operating_state',
            //'contact_number',
            //'parent_id',
            //'country_id',
            //'confirm_time',
            //'created_time',
            //'updated_time',
            //'is_active',
            //'is_approve',
            //'updated_by',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/site/stakeholders.php
    <div class="container">
        <div class="wrapper">
            <div class="row row-offcanvas row-offcanvas-left gfs-inner">
        <!-- sidebar -->
        <div class="column col-sm-3 col-xs-1 sidebar-offcanvas" id="sidebar">
            <ul class="nav" id="menu">
                <li><a href="<?= Yii::$app->urlManager->createAbsoluteUrl('site/about') ?>" ><span class="collapse in hidden-xs">About</span></a></li>
                <li><a href="<?= Yii::$app->urlManager->createAbsoluteUrl('site/how-it-works') ?>" > <span class="collapse in hidden-xs">How it Works</span></a></li>
                <li><a href="<?= Yii::$app->urlManager->createAbsoluteUrl('site/stakeholders') ?>" class="active"> <span class="collapse in hidden-xs">Stakeholders</span></a></li>
                <li><a href="<?= Yii::$app->urlManager->createAbsoluteUrl('site/board') ?>"><span class="collapse in hidden-xs">Board</span></a></li>
         
           </ul>
        </div>
        <!-- /sidebar -->

        <!-- main right col -->
        <div class="column col-sm-9 col-xs-12" id="main">
            <a href="#" data-toggle="offcanvas"><i class="fa fa-navicon fa-2x"></i></a>
           <h1 class="big-title" id="about" >Stakeholders</h1>
            <hr/>
            <article class="regular-text-left">
             
            <h4 class="regular-text-left"><b>Donors:</b></h4>
            <p class="regular-text-left">The Food Stamps are paid for by the Donors. Donors comprises of Government, Multinational Donor Agencies, Corporate Organization and benevolent individual. Donors can purchase food stamps on this website and choose an NGO to distribute the stamps to the beneficiaries or can decide to distribute the food stamps themselves.. <a style="color: green" href="<?php //echo $this->createUrl('donor/login') ?>">Become Donor</a>
                
                
                </p>
                
                
                
            <h4 class="regular-text-left"><b>NGO (Partners) :</b></h4>
            <p class="regular-text-left">Non-Governmental Organisations are validated for their appropriate registrations and address verification before they are published on the website. Only after the validation and verification exercise shall the NGO be allowed to publish their work with the communities for which they solicit the feeding program.. <a style="color: green" href="<?php //echo $this->createUrl('partner/login') ?>">Become Partner</a></p>
            <h4 class="regular-text-left"><b>FOOD VENDOR NETWORK :</b></h4>
            <p class="regular-text-left">For enquiries on joining the GFS food network or bringing the food network to your city, please email info@givefoodstamps.com</p>
            <h4 class="regular-text-left"><b>BENEFICIARY :</b></h4>
            <p class="regular-text-left">The beneficiaries are indigent and less privileged in the society living below $1 a day</p>
            </article>
        </div>
        <!-- /main -->
    </div>
</div>
    </div>
    

views/site/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Update Users: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="users-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>